In [1]:
import numpy as np

# 1.array()与asarray()
* array:将输入的数据转换为ndarray，会进行copy
* asarray：将输入的数据转换为ndarray，如果输入本身是ndarray，则不会进行copy

In [3]:
data = [1,2,3]
print(f"元数据地址为:{id(data)}")
arr = np.array(data)
print(f"arr1地址为:{id(arr)}")
print(f"数组数据为:{arr}")

元数据地址为:2711921399040
arr1地址为:2711922969840
数组数据为:[1 2 3]


In [4]:
arr2 = np.array(arr)
print(f"arr2地址为:{id(arr2)}")
print(f"arr2数组数据为:{arr2}")

arr2地址为:2711922970416
arr2数组数据为:[1 2 3]


In [5]:
arr3 = np.asarray(arr)
print(f"arr3地址为:{id(arr3)}")
print(f"arr3数组数据为:{arr3}")

arr3地址为:2711922969840
arr3数组数据为:[1 2 3]


In [6]:
arr4 = np.asarray(arr3)
print(f"arr4地址为:{id(arr4)}")
print(f"arr4数组数据为:{arr4}")

arr4地址为:2711922969840
arr4数组数据为:[1 2 3]


# 2.zeros()、ones()、empty()与zeros_like()、ones_like()、empty_like()

In [7]:
arr1 = np.zeros((2, 5))
arr2 = np.ones((2, 5))
arr3 = np.empty((2, 3))

arr4 = np.ones_like(arr1)
arr5 = np.ones_like(arr1)
arr6 = np.empty_like(arr3)

# 3.full()与full_like()

In [8]:
arr1 = np.full((2, 3), 6)
arr1

array([[6, 6, 6],
       [6, 6, 6]])

In [10]:
arr2 = np.full_like(arr1, 5)
arr2

array([[5, 5, 5],
       [5, 5, 5]])

# 4.arange()

In [11]:
arr1 = np.arange(0, 10, 2)
arr1

array([0, 2, 4, 6, 8])

# 5.linspace()与logspace()

In [12]:
arr1 = np.linspace(start=0, stop=10, num=5,endpoint=False)
arr1

array([0., 2., 4., 6., 8.])

In [14]:
arr2 = np.logspace(start=2, stop=5, num=5, base=2,endpoint=True)
arr2

array([ 4.        ,  6.72717132, 11.3137085 , 19.02731384, 32.        ])

# 6.随机数组
* random.rand()
* random.randn()
* random.randint()
* random.uniform()

In [15]:
arr1 = np.random.rand(2, 3)
arr1

array([[0.94512016, 0.22984642, 0.79840542],
       [0.24297539, 0.90516163, 0.93935802]])

In [16]:
arr2 = np.random.randn(2, 3)
arr2

array([[-0.95432122,  0.66492208,  2.70758542],
       [ 0.46236947, -1.39981801,  1.14905041]])

In [17]:
arr3 = np.random.randint(0, 10, (2, 3))
arr3

array([[2, 0, 8],
       [6, 5, 5]], dtype=int32)

In [18]:
arr4 = np.random.uniform(0, 10, (2, 3))
arr4

array([[5.77697674, 4.26409147, 7.90721353],
       [8.80268134, 7.20440295, 4.02671373]])

# 7.matrix()

In [19]:
arr1 = np.matrix("1 2; 3 4")
arr1

matrix([[1, 2],
        [3, 4]])

In [20]:
arr2 = np.matrix([[1, 2], [3, 4]])
arr2

matrix([[1, 2],
        [3, 4]])