In [1]:
import numpy as np

* bool
* int
    * int 8 uint 8
    * int 16 uint 16
    * int 32 uint 32
    * int 64 uint 64
* float
    * float 16
    * float 32
    * float 64

创建数组时可以使用dtype参数指定元素类型

In [2]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr1

array([1., 2., 3.])

In [3]:
arr2 = np.array([0.2, 2.5, 4.8], dtype=np.int16)
arr2

array([0, 2, 4], dtype=int16)

可以使用ndarray.astype()方法转换数组的元素类型

In [4]:
arr3 = arr2.astype(np.float32)
arr3

array([0., 2., 4.], dtype=float32)