In [1]:
import numpy as np

In [3]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
#获取索引为2的数据
print(arr[2])
arr[2]

2


np.int64(2)

In [6]:
# 从索引 2开始到索引9(不包含)停止，间隔为2
print(arr[2:9:2])
arr[2:9:2]

[2 4 6 8]


array([2, 4, 6, 8])

In [7]:
# 从索引2开始到最后(不包含)，默认间隔为1
print(arr[2:])

[2 3 4 5 6 7 8 9]


In [8]:
# 从索引2开始到索引9(不包含)结束，默认间隔为1
print(arr[2:9])

[2 3 4 5 6 7 8]
