In [1]:
import numpy as np

# 1.基本函数
* np.abs()
* np.ceil()
* np.floor()
* np.rint()
* np.isnan()
* np.multiply()
* np.divide()
* np.where(condition, x, y)

In [4]:
arr = np.array([1.2,2.4,2.5,3.5])
arr

array([1.2, 2.4, 2.5, 3.5])

In [5]:
np.abs(arr)

array([1.2, 2.4, 2.5, 3.5])

In [6]:
np.ceil(arr)

array([2., 3., 3., 4.])

In [7]:
np.floor(arr)

array([1., 2., 2., 3.])

In [8]:
np.rint(arr)

array([1., 2., 2., 4.])

In [10]:
np.where(arr>2,3,1)

array([1, 3, 3, 3])

# 2.统计函数
* np.mean()
* np.sum()
* np.max()
* np.min()
* np.std()
* np.var()
* np.argmax()
* np.argmin()
* np.cumsum()
* np.cumprod()

In [15]:
arr1 = np.random.randint(1, 5, (2, 3))
print(f"{arr1 = }")
print(f"{np.mean(arr1) = }")
print(f"{np.sum(arr1) = }")
print(f"{np.max(arr1) = }")
print(np.min(arr1))
print(np.std(arr1))
print(np.var(arr1))
print(np.argmax(arr1))
print(np.argmin(arr1))
print(np.cumsum(arr1))
print(np.cumprod(arr1))
print(np.cumprod(arr1, axis=1))

arr1 = array([[4, 4, 3],
       [4, 3, 2]], dtype=int32)
np.mean(arr1) = np.float64(3.3333333333333335)
np.sum(arr1) = np.int64(20)
np.max(arr1) = np.int32(4)
2
0.7453559924999298
0.5555555555555555
0
5
[ 4  8 11 15 18 20]
[   4   16   48  192  576 1152]
[[ 4 16 48]
 [ 4 12 24]]


# 3.比较函数
* np.all()
* np.any()

In [4]:
pass

# 4.排序函数
* ndarray.sort()
* np.sort()

In [5]:
pass

# 5.去重函数
* np.unique()

In [6]:
arr = np.random.randint(0,10,(3,4))
arr

array([[8, 2, 3, 2],
       [0, 4, 3, 0],
       [2, 5, 9, 7]], dtype=int32)

In [7]:
np.unique(arr)

array([0, 2, 3, 4, 5, 7, 8, 9], dtype=int32)